### ISSUE TITLE
[BUG] Vertical videos rotated and stretched

### ISSUE THREAD

**Issue by andrzej-r** [giejay/Immich-Android-TV#7]
**Describe the bug**
Vertical videos are displayed on a vertical canvas (correct) but are rotated 90Deg CCW and stretched vertically to fill the canvas.

**To Reproduce**
1. Play back a video that was recorded on a mobile phone held vertically

**Expected behavior**
The canvas orientation is correct but the video content should not be rotated, in which case vertical stretching would not be needed.

**My setup (please complete the following information):**
 - Android OS version: 9
 - Device: Sony Bravia
 - Immich app version: 1.18.1

**Comment by giejay** [comment]
Could you please upload an example video to this album? https://giejay-immich.duckdns.org/share/MW5mEqx2jClEEwLeZuQvBVL28MwwJCeJchXvBjyK5MvA_jEU693CdI1lmRPLc_BmBCU
Password: vertical

**Comment by andrzej-r** [comment]
Done.

There is also an issue with the preview thumbnail - it is displayed horizontally.

**Comment by giejay** [comment]
Hmm. For me, it's playing it like this: 

<img width="1009" alt="image" src="https://github.com/giejay/Immich-Android-TV/assets/2014373/3719d79b-0985-44e0-9d3e-ca774a33fe5e">

That's fine right? For you it's 90 degrees turned?

**Comment by andrzej-r** [comment]
Yes, your screenshot looks correct (same as in the web or android Immich app). On my TV however the canvas shape is the same but the contents is rotated 90Deg CCW and video is stretched to fit the canvas.

**Comment by giejay** [comment]
Ah yes, this was a screenshot from an emulator using Android 11. When using my Sony Bravia with Android 9, I see your issue. I had the exact same issue when playing the media with Plex, some time ago so not sure if there's a solution. I will do some research

**Comment by giejay** [comment]
I upgraded the exoplayer dependency to use media3, but the issue persists. I didnt find another solution yet so I will probably open a GitHub issue at the media3 repo

**Comment by ATG-rd** [comment]
Hi, have you perhaps received any feedback/update from media3?
Thanks

**Comment by kkmaslowski** [comment]
It's known bug in Immich: https://github.com/immich-app/immich/issues/2130

**Comment by rexkani** [comment]
I'm also hitting this bug on my fireTV installation. All vertical videos were played in vertical canvas, but the video is rotated and stretched. 

Horizontal videos works fine

**Comment by Dubsanator** [comment]
I am running into the same issue with my Sony Bravia install as well. Some videos are fine, some are rotated and stretched, being totally distorted. The closed ticket with the immich app does not resolve this issue, seems to be related to the TV app.

**Comment by giejay** [comment]
A solution from @Radiokot in the other ticket I raised seems to fix it for me as well. At least with the example video. I will release it this week, please give it a shot.

**Comment by giejay** [comment]
https://github.com/giejay/Immich-Android-TV/releases/tag/1.43

**Comment by Dubsanator** [comment]
Awesome! Do you know how long it takes to get to the play store for
updating? I see they're currently offering 1.41.

**Comment by giejay** [comment]
I need to manually roll that out, will do that tonight. Should be available tomorrow. You can also sideload it

**Comment by Dubsanator** [comment]
Attempted side load before and got this:

Performing Streamed Install
adb: failed to install app-release.apk: Failure
[INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package nl.giejay.android.tv.immich
signatures do not match previously installed version; ignoring!]

**Comment by giejay** [comment]
Yeah you do need to deinstall the current installation first probably. The key stores are different.

**Comment by Dubsanator** [comment]
Ah okay. Maybe I will just wait for the Play store update, that way I don't
have to update all of my settings again. When I originally installed it the
set as screensaver option didn't work which led me to do the ADB commands
from the start.

**Comment by giejay** [comment]
It should be available. Can you test it out?

**Comment by Dubsanator** [comment]
Sorry I meant to send a message back here. It's already updated and seems
to be working so far. Let me test a bit more and reply with another update.

**Comment by Dubsanator** [comment]
So far everything looks good! Videos are playing correctly. I am seeing a
bit of glitchy playback, but that might be an issue with the network in my
house. Thank you for the quick response and fix!!

**Comment by Dubsanator** [comment]
Checked my network here, not seeing any issues playing videos except here.
Plays for about a second, then glitches the rest of the video no matter the
length. They are the right direction, but not playing smooth.

**Comment by rexkani** [comment]
The issue is fixed! Can play vertical videos now with v1.43.
Thanks @giejay !

**Comment by giejay** [comment]
Thanks for the feedback. I will close this one. Maybe create a new issue for the smooth playing, although I'm not sure if theres anything else I can do
